<?php
       
        if ($_SERVER["REQUEST_METHOD"] == "POST") {
            // The form was submitted. Now, process the data on the server.

            // Check if the 'userName' field exists and is not empty
            if (isset($_POST['userName']) && !empty($_POST['userName'])) {
                $name = htmlspecialchars($_POST['userName']); // Sanitize input
                echo "<div class='message'>";
                echo "<h3>Hello, " . $name . "!</h3>";
                echo "<p>Your name was successfully processed on the server.</p>";
                echo "<p>This message was generated by the PHP script *before* the page was sent to your browser.</p>";
                echo "</div>";
            } else {
                echo "<div class='message' style='background-color: #fff0f0; border-color: #ff9999;'>";
                echo "<p>Please enter your name.</p>";
                echo "</div>";
            }
        }
        ?>